export const AFF_CREATE_REQUEST = "AFF_CREATE_REQUEST";
export const AFF_CREATE_SUCCESS = "AFF_CREATE_SUCCESS";
export const AFF_CREATE_FAIL = "AFF_CREATE_FAIL";
export const AFF_CREATE_RESET = "AFF_CREATE_RESET";

export const AFF_UPDATE_REQUEST = "AFF_UPDATE_REQUEST";
export const AFF_UPDATE_SUCCESS = "AFF_UPDATE_SUCCESS";
export const AFF_UPDATE_FAIL = "AFF_UPDATE_FAIL";
export const AFF_UPDATE_RESET = "AFF_UPDATE_RESET";

export const AFF_DETAILS_REQUEST = "AFF_DETAILS_REQUEST";
export const AFF_DETAILS_SUCCESS = "AFF_DETAILS_SUCCESS";
export const AFF_DETAILS_FAIL = "AFF_DETAILS_FAIL";
export const AFF_DETAILS_RESET = "AFF_DETAILS_RESET";


export const AFF_DELETE_REQUEST = "AFF_DELETE_REQUEST";
export const AFF_DELETE_SUCCESS = "AFF_DELETE_SUCCESS";
export const AFF_DELETE_FAIL = "AFF_DELETE_FAIL";
export const AFF_DELETE_RESET = "AFF_DELETE_RESET";


export const AFF_LIST_REQUEST = 'AFF_LIST_REQUEST'
export const AFF_LIST_SUCCESS = 'AFF_LIST_SUCCESS'
export const AFF_LIST_FAIL = 'AFF_LIST_FAIL'
export const AFF_LIST_RESET = 'AFF_LIST_RESET'
