export const AIM_REGISTER_REQUEST = "AIM_REGISTER_REQUEST";
export const AIM_REGISTER_SUCCESS = "AIM_REGISTER_SUCCESS";
export const AIM_REGISTER_FAIL = "AIM_REGISTER_FAIL";
export const AIM_REGISTER_RESET = "AIM_REGISTER_RESET";

export const AIM_LIST_MY_REQUEST = "AIM_LIST_MY_REQUEST";
export const AIM_LIST_MY_SUCCESS = "AIM_LIST_MY_SUCCESS";
export const AIM_LIST_MY_FAIL = "AIM_LIST_MY_FAIL";
export const AIM_LIST_MY_RESET = "AIM_LIST_MY_RESET";

export const AIM_DETAILS_REQUEST = "AIM_DETAILS_REQUEST";
export const AIM_DETAILS_SUCCESS = "AIM_DETAILS_SUCCESS";
export const AIM_DETAILS_FAIL = "AIM_DETAILS_FAIL";


export const AIM_COMPLETE_REQUEST = "AIM_COMPLETE_REQUEST";
export const AIM_COMPLETE_SUCCESS = "AIM_COMPLETE_SUCCESS";
export const AIM_COMPLETE_FAIL = "AIM_COMPLETE_FAIL";
export const AIM_COMPLETE_RESET = "AIM_COMPLETE_RESET";


export const AIM_LIST_REQUEST = 'AIM_LIST_REQUEST'
export const AIM_LIST_SUCCESS = 'AIM_LIST_SUCCESS'
export const AIM_LIST_FAIL = 'AIM_LIST_FAIL'