export const COMMITMENT_REGISTER_REQUEST = "COMMITMENT_REGISTER_REQUEST";
export const COMMITMENT_REGISTER_SUCCESS = "COMMITMENT_REGISTER_SUCCESS";
export const COMMITMENT_REGISTER_FAIL = "COMMITMENT_REGISTER_FAIL";
export const COMMITMENT_REGISTER_RESET = "COMMITMENT_REGISTER_RESET";


export const COMMITMENT_LIST_MY_REQUEST = "COMMITMENT_LIST_MY_REQUEST";
export const COMMITMENT_LIST_MY_SUCCESS = "COMMITMENT_LIST_MY_SUCCESS";
export const COMMITMENT_LIST_MY_FAIL = "COMMITMENT_LIST_MY_FAIL";
export const COMMITMENT_LIST_MY_RESET = "COMMITMENT_LIST_MY_RESET";


export const COMMITMENT_DETAILS_REQUEST = "COMMITMENT_DETAILS_REQUEST";
export const COMMITMENT_DETAILS_SUCCESS = "COMMITMENT_DETAILS_SUCCESS";
export const COMMITMENT_DETAILS_FAIL = "COMMITMENT_DETAILS_FAIL";


export const COMMITMENT_COMPLETE_REQUEST = "COMMITMENT_COMPLETE_REQUEST";
export const COMMITMENT_COMPLETE_SUCCESS = "COMMITMENT_COMPLETE_SUCCESS";
export const COMMITMENT_COMPLETE_FAIL = "COMMITMENT_COMPLETE_FAIL";
export const COMMITMENT_COMPLETE_RESET = "COMMITMENT_COMPLETE_RESET";


export const COMMITMENT_LIST_REQUEST = 'COMMITMENT_LIST_REQUEST'
export const COMMITMENT_LIST_SUCCESS = 'COMMITMENT_LIST_SUCCESS'
export const COMMITMENT_LIST_FAIL = 'COMMITMENT_LIST_FAIL'

export const CAL_ASSIGNED_REQUEST = "CAL_ASSIGNED_REQUEST";
export const CAL_ASSIGNED_SUCCESS = "CAL_ASSIGNED_SUCCESS";
export const CAL_ASSIGNED_FAIL = "CAL_ASSIGNED_FAIL";
export const CAL_ASSIGNED_RESET = "CAL_ASSIGNED_RESET";

export const READER_ASSIGNED_REQUEST = "READER_ASSIGNED_REQUEST";
export const READER_ASSIGNED_SUCCESS = "READER_ASSIGNED_SUCCESS";
export const READER_ASSIGNED_FAIL = "READER_ASSIGNED_FAIL";
export const READER_ASSIGNED_RESET = "READER_ASSIGNED_RESET";


export const CAL_ORDERS_REQUEST= "CAL_ORDERS_REQUEST"
export const CAL_ORDERS_SUCCESS= "CAL_ORDERS_SUCCESS"
export const CAL_ORDERS_FAIL= "CAL_ORDERS_FAIL"
export const CAL_ORDERS_RESET= "CAL_ORDERS_RESET"

export const READER_ORDERS_REQUEST= "READER_ORDERS_REQUEST"
export const READER_ORDERS_SUCCESS= "READER_ORDERS_SUCCESS"
export const READER_ORDERS_FAIL= "READER_ORDERS_FAIL"
export const READER_ORDERS_RESET= "READER_ORDERS_RESET"

export const CAL_UPLOAD_REQUEST= "CAL_UPLOAD_REQUEST"
export const CAL_UPLOAD_SUCCESS= "CAL_UPLOAD_SUCCESS"
export const CAL_UPLOAD_FAIL= "CAL_UPLOAD_FAIL"
export const CAL_UPLOAD_RESET= "CAL_UPLOAD_RESET"

export const READER_SELECT_REQUEST= "READER_SELECT_REQUEST"
export const READER_SELECT_SUCCESS= "READER_SELECT_SUCCESS"
export const READER_SELECT_FAIL= "READER_SELECT_FAIL"
export const READER_SELECT_RESET= "READER_SELECT_RESET"


export const COMMENT_ADD_REQUEST = "COMMENT_ADD_REQUEST";
export const COMMENT_ADD_SUCCESS = "COMMENT_ADD_SUCCESS";
export const COMMENT_ADD_FAIL = "COMMENT_ADD_FAIL";
export const COMMENT_ADD_RESET = "COMMENT_ADD_RESET";