export const CONTENT_UPDATE_REQUEST = "CONTENT_UPDATE_REQUEST";
export const CONTENT_UPDATE_SUCCESS = "CONTENT_UPDATE_SUCCESS";
export const CONTENT_UPDATE_FAIL = "CONTENT_UPDATE_FAIL";
export const CONTENT_UPDATE_RESET = "CONTENT_UPDATE_RESET";


export const CONTENT_DETAILS_REQUEST = "CONTENT_DETAILS_REQUEST";
export const CONTENT_DETAILS_SUCCESS = "CONTENT_DETAILS_SUCCESS";
export const CONTENT_DETAILS_FAIL = "CONTENT_DETAILS_FAIL";





