export const COUNSEL_REGISTER_REQUEST = "COUNSEL_REGISTER_REQUEST";
export const COUNSEL_REGISTER_SUCCESS = "COUNSEL_REGISTER_SUCCESS";
export const COUNSEL_REGISTER_FAIL = "COUNSEL_REGISTER_FAIL";
export const COUNSEL_REGISTER_RESET = "COUNSEL_REGISTER_RESET";


export const COUNSEL_LIST_MY_REQUEST = "COUNSEL_LIST_MY_REQUEST";
export const COUNSEL_LIST_MY_SUCCESS = "COUNSEL_LIST_MY_SUCCESS";
export const COUNSEL_LIST_MY_FAIL = "COUNSEL_LIST_MY_FAIL";
export const COUNSEL_LIST_MY_RESET = "COUNSEL_LIST_MY_RESET";


export const COUNSEL_DETAILS_REQUEST = "COUNSEL_DETAILS_REQUEST";
export const COUNSEL_DETAILS_SUCCESS = "COUNSEL_DETAILS_SUCCESS";
export const COUNSEL_DETAILS_FAIL = "COUNSEL_DETAILS_FAIL";


export const COUNSEL_COMPLETE_REQUEST = "COUNSEL_COMPLETE_REQUEST";
export const COUNSEL_COMPLETE_SUCCESS = "COUNSEL_COMPLETE_SUCCESS";
export const COUNSEL_COMPLETE_FAIL = "COUNSEL_COMPLETE_FAIL";
export const COUNSEL_COMPLETE_RESET = "COUNSEL_COMPLETE_RESET";


export const COUNSEL_LIST_REQUEST = 'COUNSEL_LIST_REQUEST'
export const COUNSEL_LIST_SUCCESS = 'COUNSEL_LIST_SUCCESS'
export const COUNSEL_LIST_FAIL = 'COUNSEL_LIST_FAIL'