export const FACULTY_CREATE_REQUEST = "FACULTY_CREATE_REQUEST";
export const FACULTY_CREATE_SUCCESS = "FACULTY_CREATE_SUCCESS";
export const FACULTY_CREATE_FAIL = "FACULTY_CREATE_FAIL";
export const FACULTY_CREATE_RESET = "FACULTY_CREATE_RESET";

export const FACULTY_UPDATE_REQUEST = "FACULTY_UPDATE_REQUEST";
export const FACULTY_UPDATE_SUCCESS = "FACULTY_UPDATE_SUCCESS";
export const FACULTY_UPDATE_FAIL = "FACULTY_UPDATE_FAIL";
export const FACULTY_UPDATE_RESET = "FACULTY_UPDATE_RESET";

export const FACULTY_DETAILS_REQUEST = "FACULTY_DETAILS_REQUEST";
export const FACULTY_DETAILS_SUCCESS = "FACULTY_DETAILS_SUCCESS";
export const FACULTY_DETAILS_FAIL = "FACULTY_DETAILS_FAIL";
export const FACULTY_DETAILS_RESET = "FACULTY_DETAILS_RESET";


export const FACULTY_DELETE_REQUEST = "FACULTY_DELETE_REQUEST";
export const FACULTY_DELETE_SUCCESS = "FACULTY_DELETE_SUCCESS";
export const FACULTY_DELETE_FAIL = "FACULTY_DELETE_FAIL";
export const FACULTY_DELETE_RESET = "FACULTY_DELETE_RESET";


export const FACULTY_LIST_REQUEST = 'FACULTY_LIST_REQUEST'
export const FACULTY_LIST_SUCCESS = 'FACULTY_LIST_SUCCESS'
export const FACULTY_LIST_FAIL = 'FACULTY_LIST_FAIL'
export const FACULTY_LIST_RESET = 'FACULTY_LIST_RESET'
