export const INNOVATION_REGISTER_REQUEST = "INNOVATION_REGISTER_REQUEST";
export const INNOVATION_REGISTER_SUCCESS = "INNOVATION_REGISTER_SUCCESS";
export const INNOVATION_REGISTER_FAIL = "INNOVATION_REGISTER_FAIL";
export const INNOVATION_REGISTER_RESET="INNOVATION_REGISTER_RESET"; 

export const INNOVATION_LIST_MY_REQUEST = "INNOVATION_LIST_MY_REQUEST";
export const INNOVATION_LIST_MY_SUCCESS = "INNOVATION_LIST_MY_SUCCESS";
export const INNOVATION_LIST_MY_FAIL = "INNOVATION_LIST_MY_FAIL";
export const INNOVATION_LIST_MY_RESET = "INNOVATION_LIST_MY_RESET";

export const INNOVATION_DETAILS_REQUEST = "INNOVATION_DETAILS_REQUEST";
export const INNOVATION_DETAILS_SUCCESS = "INNOVATION_DETAILS_SUCCESS";
export const INNOVATION_DETAILS_FAIL = "INNOVATION_DETAILS_FAIL";

export const INNOVATION_COMPLETE_REQUEST = "INNOVATION_COMPLETE_REQUEST";
export const INNOVATION_COMPLETE_SUCCESS = "INNOVATION_COMPLETE_SUCCESS";
export const INNOVATION_COMPLETE_FAIL = "INNOVATION_COMPLETE_FAIL";
export const INNOVATION_COMPLETE_RESET = "INNOVATION_COMPLETE_RESET";


export const INNOVATION_LIST_REQUEST = 'INNOVATION_LIST_REQUEST'
export const INNOVATION_LIST_SUCCESS = 'INNOVATION_LIST_SUCCESS'
export const INNOVATION_LIST_FAIL = 'INNOVATION_LIST_FAIL'


