export const INTERN_CREATE_REQUEST = "INTERN_CREATE_REQUEST";
export const INTERN_CREATE_SUCCESS = "INTERN_CREATE_SUCCESS";
export const INTERN_CREATE_FAIL = "INTERN_CREATE_FAIL";
export const INTERN_CREATE_RESET = "INTERN_CREATE_RESET";

export const INTERN_UPDATE_REQUEST = "INTERN_UPDATE_REQUEST";
export const INTERN_UPDATE_SUCCESS = "INTERN_UPDATE_SUCCESS";
export const INTERN_UPDATE_FAIL = "INTERN_UPDATE_FAIL";
export const INTERN_UPDATE_RESET = "INTERN_UPDATE_RESET";

export const INTERN_DETAILS_REQUEST = "INTERN_DETAILS_REQUEST";
export const INTERN_DETAILS_SUCCESS = "INTERN_DETAILS_SUCCESS";
export const INTERN_DETAILS_FAIL = "INTERN_DETAILS_FAIL";
export const INTERN_DETAILS_RESET = "INTERN_DETAILS_RESET";


export const INTERN_DELETE_REQUEST = "INTERN_DELETE_REQUEST";
export const INTERN_DELETE_SUCCESS = "INTERN_DELETE_SUCCESS";
export const INTERN_DELETE_FAIL = "INTERN_DELETE_FAIL";
export const INTERN_DELETE_RESET = "INTERN_DELETE_RESET";


export const INTERN_LIST_REQUEST = 'INTERN_LIST_REQUEST'
export const INTERN_LIST_SUCCESS = 'INTERN_LIST_SUCCESS'
export const INTERN_LIST_FAIL = 'INTERN_LIST_FAIL'
export const INTERN_LIST_RESET = 'INTERN_LIST_RESET'
