export const INTERN_FORM_REGISTER_REQUEST = "INTERN_FORM_REGISTER_REQUEST";
export const INTERN_FORM_REGISTER_SUCCESS = "INTERN_FORM_REGISTER_SUCCESS";
export const INTERN_FORM_REGISTER_FAIL = "INTERN_FORM_REGISTER_FAIL";
export const INTERN_FORM_REGISTER_RESET = "INTERN_FORM_REGISTER_RESET";


export const INTERN_FORM_DETAILS_REQUEST = "INTERN_FORM_DETAILS_REQUEST";
export const INTERN_FORM_DETAILS_SUCCESS = "INTERN_FORM_DETAILS_SUCCESS";
export const INTERN_FORM_DETAILS_FAIL = "INTERN_FORM_DETAILS_FAIL";





export const INTERN_FORM_LIST_REQUEST = 'INTERN_FORM_LIST_REQUEST'
export const INTERN_FORM_LIST_SUCCESS = 'INTERN_FORM_LIST_SUCCESS'
export const INTERN_FORM_LIST_FAIL = 'INTERN_FORM_LIST_FAIL'