export const SHARPEN_REGISTER_REQUEST = "SHARPEN_REGISTER_REQUEST";
export const SHARPEN_REGISTER_SUCCESS = "SHARPEN_REGISTER_SUCCESS";
export const SHARPEN_REGISTER_FAIL = "SHARPEN_REGISTER_FAIL";
export const SHARPEN_REGISTER_RESET = "SHARPEN_REGISTER_RESET";

export const SHARPEN_LIST_MY_REQUEST = "SHARPEN_LIST_MY_REQUEST";
export const SHARPEN_LIST_MY_SUCCESS = "SHARPEN_LIST_MY_SUCCESS";
export const SHARPEN_LIST_MY_FAIL = "SHARPEN_LIST_MY_FAIL";
export const SHARPEN_LIST_MY_RESET = "SHARPEN_LIST_MY_RESET";

export const SHARPEN_DETAILS_REQUEST = "SHARPEN_DETAILS_REQUEST";
export const SHARPEN_DETAILS_SUCCESS = "SHARPEN_DETAILS_SUCCESS";
export const SHARPEN_DETAILS_FAIL = "SHARPEN_DETAILS_FAIL";


export const SHARPEN_COMPLETE_REQUEST = "SHARPEN_COMPLETE_REQUEST";
export const SHARPEN_COMPLETE_SUCCESS = "SHARPEN_COMPLETE_SUCCESS";
export const SHARPEN_COMPLETE_FAIL = "SHARPEN_COMPLETE_FAIL";
export const SHARPEN_COMPLETE_RESET = "SHARPEN_COMPLETE_RESET";


export const SHARPEN_LIST_REQUEST = 'SHARPEN_LIST_REQUEST'
export const SHARPEN_LIST_SUCCESS = 'SHARPEN_LIST_SUCCESS'
export const SHARPEN_LIST_FAIL = 'SHARPEN_LIST_FAIL'